from enum import Enum


class Opcao(Enum):
    CRIAR_GRUPO = "-CRIAR_GRUPO-"
    MOSTRAR_GRUPO = "-MOSTRAR_GRUPO-"
    PRIMEIRO_COMBATE = "-PRIMEIRO_COMBATE-"
    SEGUNDO_COMBATE = "-SEGUNDO_COMBATE-"
    ULTIMO_COMBATE = "-ULTIMO_COMBATE-"
    COMBATES = [PRIMEIRO_COMBATE, SEGUNDO_COMBATE, ULTIMO_COMBATE]
