from enum import Enum


class MenuInicial(Enum):
    CRIAR_GRUPO = "CRIAR GRUPO"
    MOSTRAR_GRUPO = "MOSTRAR GRUPO"
    MOSTRAR_ESTATISTICAS = "MOSTRAR ESTATISTICAS"
    RESETAR_DATABASE = "RESETAR DATABASE"
    PRIMEIRO_COMBATE = 0
    SEGUNDO_COMBATE = 1
    ULTIMO_COMBATE = 2
    SAIR = "SAIR"
    COMBATES = [PRIMEIRO_COMBATE, SEGUNDO_COMBATE, ULTIMO_COMBATE]
    BOTOES_MENU_INICIAL = [
        CRIAR_GRUPO,
        MOSTRAR_GRUPO,
        MOSTRAR_ESTATISTICAS,
        RESETAR_DATABASE,
        PRIMEIRO_COMBATE,
        SEGUNDO_COMBATE,
        ULTIMO_COMBATE,
        SAIR
    ]


class MenuCriacao(Enum):
    NOME = "NOME"
    SELECIONAR_CLASSE = "SELECIONAR CLASSE"
    ESTATISTICAS_CLASSE = "ESTATISTICAS CLASSE"
    SELECIONAR_PODERES = "SELECIONAR PODERES"
    ESTATISTICAS_PODER = "ESTATISTICAS PODER"
    SELECIONAR_PODER = "SELECIONAR PODER"
    ESCOLHIDOS_PODERES = "PODERES ESCOLHIDOS"
    REMOVER_PODER = "REMOVER PODER SELECIONADO"
    CRIAR = "CRIAR PERSONAGEM"
    CONTINUAR = "CONTINUAR"
    SAIR = "SAIR"


class MenuCombate(Enum):
    ESTATISTICAS_ALVO = "ESTATISTICAS ALVOS"
    SELECIONAR_ALVOS = "SELECIONAR ALVOS"
    SELECIONAR_PODER = "SELECIONAR PODER"
    ESTATISTICAS_PODER = "ESTATISTICAS PODER"
    ATRIBUTOS = "ATRIBUTOS"
    STATUS_BATALHA = "STATUS BATALHA"
    USAR_PODER = "USAR PODER"
    CONTINUAR = "CONTINUAR"
    SAIR = "SAIR"
